### ISSUE TITLE
Setting hScroll and vScroll false doesn't work

### ISSUE THREAD

**Issue by Changilainen** [cubiq/2-way-iScroll#5]
I tried to set hScroll and vScroll false in twis.js file but scrolling on both ways still keep happening. Doesn't it suppose to prevent horizontal and/or vertical scrolling if I set the values false?

**Comment by cubiq** [comment]
you can't stop v/h scrolling in the 2-way-iscroll... it wouldn't be 2-way otherwise :)

**Comment by Changilainen** [comment]
Oh, okay :) Thanks for your quick answer!
Reason I asked is I want to have two vertical scrolling areas on one page just like in iScroll4's iPad example and still keep horizontal scrolling for changing pages. I was able to combine iScroll4's iPad example with 2-Way iScroll's example and I need to stop vertical scrolling on 2-Way iScroll's example so the whole page wouldn't scroll, only the 2 scrolling areas. Any hint how could I have 2 scrolling areas instead of one in 2-Way iScroll's example?
